#! /usr/bin/env python
import sys
from pony_build.client import BuildCommand, TestCommand, do, send, \
     TempDirectoryContext, SetupCommand, GitClone, check, parse_cmdline
import os
import tempfile
import shutil

options, args = parse_cmdline()

python_exe = 'python2.5'
if args:
    python_exe = args[0]

###

repo_url = 'git://github.com/django/django.git'

tags = [python_exe, 'sqlite', 'ilovepwnies']
name = 'django'

###
server_url = options.server_url 

if not options.force_build:
    #if not check(name, server_url, tags=tags):
    #    print 'check build says no need to build; bye'
    #    sys.exit(0)
    pass

commands = [ GitClone(repo_url),
             TestCommand(['python', '../tests/runtests.py', '--settings=test.settings'],
                         name='run tests', run_cwd='django')
             ]

context = TempDirectoryContext(options.cleanup_temp)
results = do(name, commands, context=context)
client_info, reslist = results

if options.report:
    print 'result: %s; sending' % (client_info['success'],)
    send(server_url, results, tags=tags)
else:

    print 'build result:'

    import pprint
    pprint.pprint(client_info)
    pprint.pprint(reslist)

    print '(NOT SENDING BUILD RESULT TO SERVER)'

if not client_info['success']:
    sys.exit(-1)
